# Generated by Django 5.1.4 on 2025-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(default=101, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(blank=True, to="myapp.course"),
        ),
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
