# Generated by Django 5.1.4 on 2025-01-18 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_name_student_first_name_course_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
