# Generated by Django 5.1.4 on 2025-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_student_dob_alter_student_enrollment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
